import './components/cookie.js';
import './components/header.js';
import './components/location.js';
import './components/search.js';
import './components/transferBlocks.js';
import './components/burger.js';
import './components/swipers.js';
import './components/accordion.js';
import './components/modal.js';
import './components/tabs.js';
import './components/add-card.js';
import './components/radio.js';
import './components/order.js';
import './components/counter.js';
import './components/favorite.js';
import './components/card.js';
import './components/anchor-scroll.js';
import './components/rating.js'
import './components/review.js'
import './components/choices.js'
import './components/form.js'
import './components/btn-back.js';